### ISSUE TITLE
Last commit broke hand tracking

### ISSUE THREAD

**Issue by A1igator** [MephestoKhaan/HandPosing#25]
Firstly, it fixed all controller issues to thanks for that! Hand tracking doesn't track in play mode anymore, while it snaps properly. In build mode,  it tracks the hand but no longer snaps.

**Comment by MephestoKhaan** [comment]
Oh crap!  Thanks for that I will fix on Monday.
So problem would be regarding the order in which operations happen compared
to the OvRCameraRig updates.

I don't have a ton of time for this repo at moment sadly, So apologies for
not testing it as throughoutly as I should.

**Comment by MephestoKhaan** [comment]
I think I fixed it, check the latest package or pull from the repo.
