### ISSUE TITLE
?use of HandPosing without Oculus Link

### ISSUE THREAD

**Issue by JoaoM07** [MephestoKhaan/HandPosing#36]
Hi! I'm trying to record a hand pose of grabbing a vault dial. I only have the Quest linked to the laptop to build and run the APK. Is there a way to record the pose without the Oculus Link? Also how would I keep the dial fixed and only rotating along the Z axis?
Big thanks

**Comment by MephestoKhaan** [comment]
Hi Joao,  I just pushed a new version to `master` that will help you with this. Please integrate the latest package (not .unityPackage from releases, but the Package Manager).


Then follow the new section `Posing the hands WITHOUT hand tracking` in the WIKI: https://github.com/MephestoKhaan/HandPosing/wiki/Pose-Recording

And let me know if you run into any issues :)

**Comment by JoaoM07** [comment]
Big thanks for this. However, I'm struggling to install stuff from Git on the Package Manager. I've installed Git. It's in the windows path but nothing. Any ideas on to how to bypass this?

**Comment by MephestoKhaan** [comment]
I am not sure if git is needed to install this. HAve you tried like so?:
https://gyazo.com/f14da2f146d6f9dac6c2ef4b4382611c

Alternatively, you can just download the .zip, and use "load from Disk..."
![image](https://user-images.githubusercontent.com/4976810/100093950-8ba86200-2e58-11eb-8efc-ade39737be90.png)

**Comment by JoaoM07** [comment]
Managed to install it using the load from disk! thanks. Will let you know how it works shortly. Thanks again.
