### ISSUE TITLE
Can't find CanMove option 

### ISSUE THREAD

**Issue by JoaoM07** [MephestoKhaan/HandPosing#37]
Hi again. After reading you wiki regarding snapping behaviours, I was trying to find the CAnMove option you talk about so I can leave the Grabbable dial in the same place when I grab it. I can't find it anywhere. Any tips?
Kind regards
J.

**Comment by MephestoKhaan** [comment]
Sorry I am still in the process of updating the docs. 

Certainly the "CanMove" option has gone, as it felt too specific. but you have 2 alternatives:

### Modify the grabbable code a tiny bit 
In the Grabbable, you can replace the `MoveTo` method with

```

        public bool canMove = true;

        public virtual void MoveTo(Vector3 desiredPos, Quaternion desiredRot)
        {
            if(canMove)
            {
                this.transform.position = desiredPos;
                this.transform.rotation = desiredRot;
            }
        }
```

or even better, inherit from `Grabbable.cs` and override that `MoveTo`.

This way you will get a toggle in the grabbable to stop it from moving, make sure to disable "Snap Back" in the snap points though.

Keep in mind you could also make the hand easily slide! So this could be very handy if you are using a hand-rail for example.


### Use physics

Depending on your usecase, you might want to use `PhysicsGrabbable.cs` instead and add a FixedJoint to the item. But I suggest the solution above.

**Comment by MephestoKhaan** [comment]
Enabled the "unmovable" option again at the Grabbable
