### ISSUE TITLE
Unity 2020.3 Integration

### ISSUE THREAD

**Issue by Aoost** [MephestoKhaan/HandPosing#39]
Hi there, has I had to update my project to Unity 2020 as a requirement for an asset I am using.

Some of the required packages seem to have been removed from the 2020 package manager: 

      * Oculus Android (2.38.6)
      * Oculus Desktop (2.38.4)
      * OpenVR Desktop (2.0.5)
      * XR Legacy Input Helpers (1.3.11)
      
    - has this repo been callibrated to work in URP for Unity 2020.3.2f1 ?

**Comment by MephestoKhaan** [comment]
Thanks for the heads up. I'll review this ASAP.

**Comment by KTRosenberg** [comment]
How is it going? I'd love to try this out in a later version of Unity.

**Comment by Aoost** [comment]
We ended up going back to 2019.3

**Comment by MephestoKhaan** [comment]
Hey Aoost!

I did a small update with other stuff last week and am planning to jump
into 2020 support on Monday. See how far I can take it in 5 days. Sorry
about the delays, had to attend other more pressing projects.

**Comment by KTRosenberg** [comment]
I was hoping that the author might have tried. hmm

**Comment by KTRosenberg** [comment]
> Hey Aoost! I did a small update with other stuff last week and am planning to jump into 2020 support on Monday. See how far I can take it in 5 days. Sorry about the delays, had to attend other more pressing projects.
> […](#)

Hi. Even though Aoost ended up just reverting, I’d be interested in using this with the latest version of Unity for some research using advanced hand tracking examples. This would be a super useful resource.

**Comment by MephestoKhaan** [comment]
> > Hey Aoost! I did a small update with other stuff last week and am planning to jump into 2020 support on Monday. See how far I can take it in 5 days. Sorry about the delays, had to attend other more pressing projects.
> > […](#)
> 
> Hi. Even though Aoost ended up just reverting, I’d be interested in using this with the latest version of Unity for some research using advanced hand tracking examples. This would be a super useful resource.

Great! Working on this today. You will need support for the XR Plugin Manager I presume, hope to have some good news during this week

**Comment by MephestoKhaan** [comment]
I see the XR Plugin Manager does have a Dependency  on `XR Legacy Input Helpers (1.3.11)` and imports it automatically.

**Comment by KTRosenberg** [comment]
Thanks a lot for looking into this!
