### ISSUE TITLE
Generate hand animations

### ISSUE THREAD

**Issue by MephestoKhaan** [MephestoKhaan/HandPosing#4]
Having a rigged hand without animations. We could use the hand tracking to generate the animation states (pointing, doing "OK", horns etc) to feed an Animator.

**Comment by kmoore-riphaina** [comment]
I've been writing code independently that performs this function, i'm currently taking a look at the this code base to see if it can be integrated.

**Comment by MephestoKhaan** [comment]
Integrated some code in develop! Soon in master when the docs are written
