### ISSUE TITLE
Minor suggestions

### ISSUE THREAD

**Issue by sohailshafiiWk** [MephestoKhaan/HandPosing#41]
Here are few minor suggestions that you might find useful:

- `OnGrabAttemp` -> `OnGrabAttempt` (missing final "t"). I've noticed a similar issue `BaseGrabber`
- Are the `{ get; set; }` on the `Action`s for `IGrabNotifier` necessary?

**Comment by MephestoKhaan** [comment]
#41

**Comment by sohailshafiiWk** [comment]
So I have seen examples such as `event Action<Args> Foo;` on interfaces, which means in all cases you probably don't need `get; set;`

**Comment by sohailshafiiWk** [comment]
btw i don't see the change in develop, did you push to the public repo?
