### ISSUE TITLE
Have pure "object to hand" snap mode

### ISSUE THREAD

**Issue by sohailshafiiWk** [MephestoKhaan/HandPosing#42]
This one will take a bit of work to figure out. There are two types of grabbing under consideration here:

1. Object-to-hand: Hand is stationary (i.e. does not reorient) and object orients to the hand upon grabbing. The closest is pose is snapped to, but the hand does not rotate itself to do so because the object moves toward the hand.
2. Hand-to-object: Object does not reorient itself; the hand puppet simply snaps to a selected pose.

If "snap back" if false on a snap point then hand-to-object is easily satisfied. This is a seen with the poses gallery's ring, for instance.

However if snap back is true, then in the current implementation it appears that both the hand and object move toward each other. This can be seen with the sword in the released sample. I think "snap back" should be an enum that allows the two behaviors above, along with what is currently implemented (which can be a "both object-to-hand and hand-to-object"). But if that requires changing too many assets, maybe there should be another boolean that allows pure "object-to-hand" behavior.

I had to work on other stuff today but tomorrow I can see how this should be implemented. Please let me know if you have any helpful pointers.

**Comment by MephestoKhaan** [comment]
Ready in develop
