### ISSUE TITLE
IsFingerHighConfidence in SkeletonDataProviderOVR returns true by default

### ISSUE THREAD

**Issue by sohailshafiiWk** [MephestoKhaan/HandPosing#45]
I'm wondering if that's expected behavior? If `PosingIDsToFinger` doesn't have the value in dictionary, should it return false or am I reading that wrong?

**Comment by MephestoKhaan** [comment]
Good question. And sorry for the super-delayed answer.

That Dictionary actually has all fingers in it, except for
```
        Invalid,
        Hand_Start,
```

Which are not fingers. So it does not really meatters if it returns `true` or `false`.
I guess for clarity it should return `false` so I will change it :)
