### ISSUE TITLE
Private _grabPoints

### ISSUE THREAD

**Issue by uurha** [MephestoKhaan/HandPosing#46]
@MephestoKhaan Good day, sir. Can you please make field `_grabPoints` in class `Grabbable` `protected` instead `private`? We are using hand posing to improve grab system in our app and we have procedural meshes and for these meshes we need to update grab points. Base system implemented in samples currently efficient for our purposes and create full Grabbable-Grabber implementation will take long time.

**Comment by MephestoKhaan** [comment]
I imagine at this point you changed it yourself in the code. But I have gone and add it as requested to the Grabbable.

You can update using the Unity Package Manager as I have not increased the version for this tweak.
