### ISSUE TITLE
Hand Physics Issues

### ISSUE THREAD

**Issue by downtown76** [MephestoKhaan/HandPosing#47]
Unsure how to configure hand physics properly to avoid fingers moving through objects prior to grabbing.

**Comment by MephestoKhaan** [comment]
Usually they don't get along very well (Grabbing and pushing with physics) but one idea that can alleviate one fighting each other is to set the tips to be triggers and leave the rest of the capsules on. 

![image](https://user-images.githubusercontent.com/4976810/130242715-b7e90126-22cb-44c9-b7d7-d0740a81edb4.png)

For a full physics solution that is completely dynamic that would be a different product all together, less controllable and CPU intensive but I suggest you look for HPTK.
